from __future__ import annotations

from models import Combination, Decision, GENERATED, GeneratedCase


def render_case(combination: Combination, decision: Decision) -> GeneratedCase:
    if decision.status != GENERATED:
        raise ValueError(f"cannot render non-generated combination: {decision.status}")
    if combination.vector != "none" and combination.cmo != "no_cmo":
        body = _vector_cmo_body(combination)
    elif combination.memory_event == "scalar_pair":
        body = _scalar_body(combination)
    elif combination.memory_event in {"vector_load", "vector_store"}:
        body = _vector_body(combination)
    elif combination.memory_event == "cmo":
        body = _cmo_body(combination)
    elif combination.memory_event == "ifetch":
        body = _ifetch_body(combination)
    else:
        body = _observation_body(combination)

    comments = [
        f"(* generated by Litmus-link; category={combination.category}; rvwmo_class={decision.rvwmo_class} *)",
        f"(* expected_kind={decision.expected_kind}; requires={','.join(decision.requires)} *)",
    ]
    return GeneratedCase(combination, decision, "\n".join([f"RISCV {combination.name}", *comments, body]).rstrip() + "\n")


def _scalar_body(combination: Combination) -> str:
    return r""""PodWW Rfe Fre"
{
0:x5=1; 0:x6=x; 0:x7=y;
1:x6=y; 1:x8=x;
}
 P0          | P1          ;
 sw x5,0(x6) | lw x5,0(x6) ;
 fence rw,rw | lw x7,0(x8) ;
 sw x5,0(x7) |             ;
exists
(1:x5=1 /\ 1:x7=0)"""


def _vector_body(combination: Combination) -> str:
    load_or_store = _vector_instruction(combination)
    setup = "vsetvli x10,x11,e32,m1,ta,ma"
    if combination.memory_event == "vector_store" or combination.vector.endswith("store"):
        return f""""Vector memory observation"
{{
0:x5=1; 0:x6=x; 0:x7=y; 0:x9=4; 0:x11=4;
1:x6=y; 1:x8=x;
}}
 P0             | P1          ;
 {setup:<14} | lw x5,0(x6) ;
 {load_or_store:<14} | fence rw,rw ;
 fence rw,rw    | lw x7,0(x8) ;
 sw x5,0(x7)    |             ;
exists
(1:x5=1)"""
    return f""""Vector memory observation"
{{
0:x5=1; 0:x6=x; 0:x7=y;
1:x6=y; 1:x8=x; 1:x9=4; 1:x11=4;
}}
 P0          | P1             ;
 sw x5,0(x6) | {setup:<14} ;
 fence rw,rw | {load_or_store:<14} ;
 sw x5,0(x7) | lw x7,0(x8)    ;
exists
(1:x7=0)"""


def _cmo_body(combination: Combination) -> str:
    cmo_lines = _cmo_lines(combination)
    cmo_block = "\n ".join(f"{line:<18} | lw x7,0(x8) ;" if index == 0 else f"{line:<18} |             ;" for index, line in enumerate(cmo_lines))
    return f""""CMO/PBMT observation"
{{
0:x5=1; 0:x6=x; 0:x7=y;
1:x6=y; 1:x8=x;
}}
 P0                 | P1          ;
 sw x5,0(x6)        | lw x5,0(x6) ;
 {cmo_block}
 sw x5,0(x7)        |             ;
exists
(1:x5=1)"""


def _vector_cmo_body(combination: Combination) -> str:
    vector_line = _vector_instruction(combination)
    cmo_lines = _cmo_lines(combination)
    p0_lines = ["vsetvli x10,x11,e32,m1,ta,ma", vector_line, *cmo_lines, "sw x5,0(x7)"]
    p1_lines = ["lw x5,0(x6)", "fence rw,rw", "lw x7,0(x8)"]
    rows = []
    for index in range(max(len(p0_lines), len(p1_lines))):
        left = p0_lines[index] if index < len(p0_lines) else ""
        right = p1_lines[index] if index < len(p1_lines) else ""
        rows.append(f" {left:<26} | {right:<13} ;")
    table = "\n".join(rows)
    return f""""Vector/CMO cross observation"
{{
0:x5=1; 0:x6=x; 0:x7=y; 0:x9=4; 0:x11=4;
1:x6=y; 1:x8=x;
}}
 P0                         | P1            ;
{table}
exists
(1:x5=1)"""


def _ifetch_body(combination: Combination) -> str:
    return r""""Instruction fetch observation"
Variant=self
{
0:t0=instr:"li t6, 2"; 0:a1=P1:mod; 0:a2=flag; 0:t1=1;
1:a2=flag;
}
 P0           | P1                ;
 sw t0,0(a1)  | lw s0,0(a2)       ;
 fence rw,rw  | fence.i           ;
 sw t1,0(a2)  | mod:              ;
              | li t6,1           ;
              | mv s1,t6          ;
exists (1:s0=1 /\ 1:s1=1)"""


def _observation_body(combination: Combination) -> str:
    return """"Hardware observation"
{
0:x5=1; 0:x6=x; 0:x7=y;
1:x6=y; 1:x8=x;
}
 P0          | P1          ;
 sw x5,0(x6) | lw x5,0(x6) ;
 fence rw,rw | lw x7,0(x8) ;
 sw x5,0(x7) |             ;
exists
(1:x5=1)"""


def _vector_instruction(combination: Combination) -> str:
    table = {
        "unit_load": "vle32.v v8,(x6)",
        "unit_store": "vse32.v v8,(x6)",
        "strided_load": "vlse32.v v8,(x6),x9",
        "strided_store": "vsse32.v v8,(x6),x9",
        "indexed_ordered_load": "vloxei32.v v8,(x6),v4",
        "indexed_unordered_load": "vluxei32.v v8,(x6),v4",
        "indexed_ordered_store": "vsoxei32.v v8,(x6),v4",
        "indexed_unordered_store": "vsuxei32.v v8,(x6),v4",
        "segment_load": "vlseg2e32.v v8,(x6)",
        "segment_store": "vsseg2e32.v v8,(x6)",
        "fof_load": "vle32ff.v v8,(x6)",
        "fof_segment_load": "vlseg2e32ff.v v8,(x6)",
        "cross_page": "vse32.v v8,(x6)" if combination.memory_event == "vector_store" else "vle32.v v8,(x6)",
    }
    return table.get(combination.vector, "vle32.v v8,(x6)")


def _cmo_lines(combination: Combination) -> list[str]:
    if combination.cmo == "flush_sync":
        return ["fence iorw,iorw", "cbo.flush 0(x6)", "fence iorw,iorw"]
    op = {
        "clean": "cbo.clean 0(x6)",
        "flush": "cbo.flush 0(x6)",
        "inval": "cbo.inval 0(x6)",
        "inval_as_flush": "cbo.inval 0(x6)",
        "zero": "cbo.zero 0(x6)",
    }.get(combination.cmo, "fence rw,rw")
    return [op]
