from __future__ import annotations

from litmus_ir import LitmusCaseIR, build_litmus_ir_cases
from models import Combination, Decision, GENERATED, GeneratedCase


def render_case(combination: Combination, decision: Decision) -> GeneratedCase:
    return render_cases(combination, decision)[0]


def render_cases(combination: Combination, decision: Decision) -> list[GeneratedCase]:
    if decision.status != GENERATED:
        raise ValueError(f"cannot render non-generated combination: {decision.status}")
    return [GeneratedCase(combination, decision, render_ir(case_ir), case_ir=case_ir) for case_ir in build_litmus_ir_cases(combination, decision)]


def render_ir(case_ir: LitmusCaseIR) -> str:
    comments = [
        f"(* generated by Litmus-link; skeleton={case_ir.skeleton}; variant={case_ir.variant}; model={case_ir.model} *)",
        f"(* cycle={case_ir.cycle} *)",
        f"(* expected_outcome={case_ir.expected_outcome} *)",
    ]
    return "\n".join(
        [
            f"RISCV {case_ir.name}",
            f'"{case_ir.cycle}"',
            *comments,
            _render_init(case_ir),
            _render_threads(case_ir),
            "exists",
            case_ir.exists,
            "",
        ]
    )


def _render_init(case_ir: LitmusCaseIR) -> str:
    return "{\n" + "\n".join(case_ir.init_lines) + "\n}"


def _render_threads(case_ir: LitmusCaseIR) -> str:
    headers = [f"P{index}" for index in range(len(case_ir.harts))]
    width = max(16, max((len(event.instruction) for hart in case_ir.harts for event in hart), default=0) + 2)
    lines = [" " + " | ".join(f"{header:<{width}}" for header in headers) + ";"]
    max_rows = max((len(hart) for hart in case_ir.harts), default=0)
    for row in range(max_rows):
        columns = []
        for hart in case_ir.harts:
            instruction = hart[row].instruction if row < len(hart) else ""
            columns.append(f"{instruction:<{width}}")
        lines.append(" " + " | ".join(columns) + ";")
    return "\n".join(lines)
